---
# handlers file for httpd
- name: save httpd details
  copy:
    content: >
      {
        "{{ httpd_facts.stdout[1:-3] }}",
        "installed": "{{ ansible_date_time.iso8601 }}"
      }
    dest: /etc/ansible/facts.d/httpd.fact
  become: yes