---
# handlers file for httpd_app
- name: restart httpd
  become: yes
  service:
    name: httpd
    state: restarted

- name: save httpd_app details
  copy:
    content: >
      {
        "ProxyPass /" : "http://{{ service_address }}:{{ app_port }}/{{ app_name }}/",
        "deployed": "{{ ansible_date_time.iso8601 }}"
      }
    dest: "/etc/ansible/facts.d/{{ service_name }}_app.fact"
  become: yes