---
# tasks file for httpd
- name: 'Install httpd'
  become: yes
  yum:
    name: httpd
    state: present
  notify:
    - save httpd details

- name: 'Started httpd'
  become: yes
  service:
    name: httpd
    enabled: yes
    state: started

- name: get tomcats facts
  shell: httpd -version 2>&1 | sed 's/$/",/;s/^/"/;s/:/":"/'
  register: httpd_facts